# This rule is not used by the project unbind-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to app.unbind.app resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: unbind-operator
    app.kubernetes.io/managed-by: kustomize
  name: app-viewer-role
rules:
- apiGroups:
  - app.unbind.app
  resources:
  - apps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.unbind.app
  resources:
  - apps/status
  verbs:
  - get
