---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.unbind.app
  resources:
  - apps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.unbind.app
  resources:
  - apps/finalizers
  verbs:
  - update
- apiGroups:
  - app.unbind.app
  resources:
  - apps/status
  verbs:
  - get
  - patch
  - update
