apiVersion: app.unbind.cloud/v1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: unbind-operator
    app.kubernetes.io/managed-by: kustomize
  name: app-sample
spec:
  # TODO(user): Add fields here
